### ISSUE TITLE
how to add Gridview as last item

### ISSUE THREAD

**Issue by gllokesh** [gdgriga/android-parallax-listview#1]
I want to add Gridview as a last item. Please help me.Thanks in advance

**Comment by echoAlexey** [comment]
customize R.layout.last_element with gridview. ;)

**Comment by gllokesh** [comment]
I tried but problem with gridview height. how we will increase gridview height??

**Comment by echoAlexey** [comment]
// Determine which part of visible area a fully expanded view should take.
    private static final float FULL_VIEW_SCREEN_PART = 0.6f;
    private static final float COLLAPSED_VIEW_SCREEN_PART = 0.3f;

well. this code is not intended to be reused in production. it's an example.
